use compositor_engine::*;
fn u16(v:&mut Vec<u8>,n:u16){v.extend(n.to_be_bytes());}
fn u32(v:&mut Vec<u8>,n:u32){v.extend(n.to_be_bytes());}
fn length(v:&mut Vec<u8>,n:usize,big:bool){if big {v.extend((n as u64).to_be_bytes())}else{u32(v,n as u32)}}
fn block(v:&mut Vec<u8>,key:&[u8;4],bytes:&[u8]){v.extend(b"8BIM");v.extend(key);u32(v,bytes.len() as u32);v.extend(bytes);if bytes.len()%2!=0 {v.push(0);}}
#[derive(Clone)]
struct FixtureLayer {name:&'static str,section:u32,clipping:bool,mask:bool,hidden:bool,extra:Vec<u8>,legacy:Option<Vec<u8>>,no_pixels:bool,color:[u8;4],opacity:u8,blend:[u8;4]}
fn fixture(big:bool,rle:bool,layers:&[FixtureLayer])->Vec<u8>{
    let mut out=b"8BPS".to_vec();u16(&mut out,if big{2}else{1});out.extend([0;6]);u16(&mut out,3);u32(&mut out,2);u32(&mut out,2);u16(&mut out,8);u16(&mut out,3);u32(&mut out,0);u32(&mut out,0);
    let mut records=Vec::new();u16(&mut records,layers.len() as u16);let mut planes=Vec::new();
    for l in layers {
        for n in [0,0,2,2] {u32(&mut records,n);}let count=if l.no_pixels{0}else if l.mask{5}else{4};u16(&mut records,count);
        for id in [-1i16,0,1,2,-2].into_iter().take(count as usize) {
            let values=if id== -1 {[l.color[3];4]}else if id== -2 {[0,255,128,255]}else{[l.color[id as usize];4]};let mut bytes=Vec::new();u16(&mut bytes,if rle{1}else{0});
            if rle {for _ in 0..2 {if big{u32(&mut bytes,3)}else{u16(&mut bytes,3)}}for row in values.chunks(2){bytes.push(1);bytes.extend(row);}}else{bytes.extend(values);}
            u16(&mut records,id as u16);length(&mut records,bytes.len(),big);planes.extend(bytes);
        }
        records.extend(b"8BIM");records.extend(if l.section==0 {&l.blend}else{b"pass"});records.extend([l.opacity,l.clipping as u8,if l.hidden{2}else{0},0]);let mut extra=Vec::new();
        if l.mask {u32(&mut extra,20);for n in [0,0,2,2] {u32(&mut extra,n);}extra.extend([255,0,0,0]);}else{u32(&mut extra,0);}u32(&mut extra,0);if let Some(name)=&l.legacy {extra.push(name.len() as u8);extra.extend(name);extra.extend(vec![0;(4-(name.len()+1)%4)%4]);}else{extra.extend([0,0,0,0]);}
        let mut name=Vec::new();let units:Vec<_>=l.name.encode_utf16().collect();u32(&mut name,units.len() as u32);for n in units {u16(&mut name,n);}if l.legacy.is_none(){block(&mut extra,b"luni",&name);}
        if l.section!=0 {block(&mut extra,b"lsct",&l.section.to_be_bytes());}extra.extend(&l.extra);u32(&mut records,extra.len() as u32);records.extend(extra);
    }
    records.extend(planes);if records.len()%2!=0{records.push(0);}let mut section=Vec::new();length(&mut section,records.len(),big);section.extend(records);u32(&mut section,0);length(&mut out,section.len(),big);out.extend(section);
    u16(&mut out,0);out.extend([70;12]);out
}
fn pixel(name:&'static str)->FixtureLayer {FixtureLayer{name,section:0,clipping:false,mask:false,hidden:false,extra:Vec::new(),legacy:None,no_pixels:false,color:[80,110,140,128],opacity:200,blend:*b"norm"}}
#[test]fn file_order_keeps_a_screen_overlay_above_an_opaque_background(){
    // Independent of private samples: the Mac reader consumes file records bottom-first.
    // Reversing these records hides the overlay behind the opaque background.
    for big in [false,true] {for rle in [false,true] {
        let mut bottom=pixel("Background");bottom.color=[40,80,120,255];bottom.opacity=255;
        let mut top=pixel("Screen overlay");top.color=[160,0,0,255];top.opacity=255;top.blend=*b"scrn";
        let imported=psd::read(&fixture(big,rle,&[bottom,top]),MAX_PIXELS,MAX_PIXELS).unwrap();
        assert_eq!(imported.document.layers.iter().map(|l|l.name.as_str()).collect::<Vec<_>>(),["Background","Screen overlay"]);
        let rendered=decode_package_png(&compositor::export_png(&imported.document).unwrap()).unwrap();
        assert!(rendered.pixel(0,0)[0]>40,"Screen overlay must contribute to the export");
        assert_eq!(&rendered.pixel(0,0)[1..],&[80,120,255]);
        let reopened=open_package(&save_package(&imported.document).unwrap()).unwrap();
        assert_eq!(compositor::export_png(&reopened).unwrap(),compositor::export_png(&imported.document).unwrap());
    }}
}
#[test]fn pixel_less_adjustments_do_not_spend_the_image_budget(){
    let mut levels=pixel("Levels");levels.no_pixels=true;let mut data=2u16.to_be_bytes().to_vec();for _ in 0..29{for n in [0,255,0,255,100]{u16(&mut data,n);}}block(&mut levels.extra,b"levl",&data);
    for big in [false,true]{let imported=psd::read(&fixture(big,true,&[FixtureLayer{name:levels.name,section:0,clipping:false,mask:false,hidden:false,extra:levels.extra.clone(),legacy:None,no_pixels:true,color:levels.color,opacity:levels.opacity,blend:levels.blend}]),0,0).unwrap();assert_eq!(imported.document.layers.len(),1);assert!(imported.document.layers[0].extra.adjustment.is_some());assert_eq!(imported.document.used_pixels(),0);}
}
#[test]fn psd_and_psb_raw_and_packbits_preserve_unicode_alpha_and_mask(){for big in [false,true] {for rle in [false,true] {let mut l=pixel("河流😀");l.mask=true;l.hidden=true;let imported=psd::read(&fixture(big,rle,&[l]),MAX_PIXELS,MAX_PIXELS).unwrap();let l=&imported.document.layers[0];assert_eq!(l.name,"河流😀");assert!(!l.visible);assert_eq!(l.pixels.as_ref().unwrap().pixel(0,0),[40,55,70,128]);assert_eq!(l.mask.as_ref().unwrap().pixels.bytes(),&[0,255,128,255]);assert_eq!(l.opacity,200./255.);assert!(imported.conversions.is_empty());}}}
#[test]fn groups_and_clipping_resolve_bottom_to_top(){let mut group=pixel("Folder");group.section=1;let mut divider=pixel("Divider");divider.section=3;let mut clipped=pixel("Clipped");clipped.clipping=true;
    for big in [false,true] {let imported=psd::read(&fixture(big,true,&[divider.clone(),pixel("Base"),clipped.clone(),group.clone()]),MAX_PIXELS,MAX_PIXELS).unwrap();let layers=&imported.document.layers;assert_eq!(layers.len(),3);assert_eq!(layers[0].name,"Base");assert_eq!(layers[1].mask_source_id,Some(layers[0].id));assert!(layers[2].is_group);assert_eq!(layers[0].parent_id,Some(layers[2].id));assert_eq!(layers[1].parent_id,layers[0].parent_id);}}
#[test]fn supported_levels_and_unsupported_types_are_reported(){let mut levels=pixel("Levels");let mut data=Vec::new();u16(&mut data,2);for _ in 0..29 {for n in [20,220,0,255,125] {u16(&mut data,n)}}block(&mut levels.extra,b"levl",&data);let mut unsupported=pixel("Unsupported");block(&mut unsupported.extra,b"post",&[0,3]);let mut smart=pixel("Smart");block(&mut smart.extra,b"SoLd",&[]);
    let i=psd::read(&fixture(false,false,&[smart,unsupported,levels]),MAX_PIXELS,MAX_PIXELS).unwrap();assert_eq!(i.document.layers.len(),2);assert_eq!(i.document.layers[1].extra.adjustment.as_ref().unwrap().levels.ranges[0].gamma,1.25);assert!(i.conversions.iter().any(|c|c.layer_name=="Unsupported"&&c.message.contains("skipped")));assert!(i.conversions.iter().any(|c|c.layer_name=="Smart"&&c.message.contains("rasterized")));}
#[test]fn import_is_atomic_and_all_layers_are_one_undo_step(){let mut e=Engine::new();let id=e.new_document(8,8,true).unwrap();let before=e.state(id).unwrap();let bytes=fixture(false,true,&[pixel("Top"),pixel("Bottom")]);let (_,notices)=e.import_psd(Some(id),&bytes,None).unwrap();assert!(notices.is_empty());assert_eq!(e.state(id).unwrap().undo_depth,before.undo_depth+1);e.undo(id).unwrap();assert_eq!(e.state(id).unwrap().layers.len(),before.layers.len());let state=e.state(id).unwrap();assert!(e.import_psd(Some(id),&bytes[..bytes.len()/2],None).is_err());assert_eq!(e.state(id).unwrap(),state);}
#[test]fn invalid_headers_sections_budgets_and_every_truncation_are_refused(){let bytes=fixture(true,true,&[pixel("Test")]);for n in 0..bytes.len()-14 {assert!(psd::read(&bytes[..n],MAX_PIXELS,MAX_PIXELS).is_err(),"truncation {n}");}assert!(psd::read(&bytes,3,MAX_PIXELS).is_err());let mut wrong=bytes.clone();wrong[23]=16;assert!(psd::read(&wrong,MAX_PIXELS,MAX_PIXELS).is_err());let mut wrong=bytes.clone();wrong[25]=4;assert!(psd::read(&wrong,MAX_PIXELS,MAX_PIXELS).is_err());let mut wrong=bytes.clone();wrong[18..22].copy_from_slice(&u32::MAX.to_be_bytes());assert!(psd::read(&wrong,MAX_PIXELS,MAX_PIXELS).is_err());}
#[test]fn save_reopen_retains_imported_structure(){let mut l=pixel("Masked");l.mask=true;let i=psd::read(&fixture(false,true,&[l]),MAX_PIXELS,MAX_PIXELS).unwrap();let pkg=save_package(&i.document).unwrap();let reopened=open_package(&pkg).unwrap();assert_eq!(reopened.manifest(),i.document.manifest());assert_eq!(reopened.layers[0].pixels.as_ref().unwrap().bytes(),i.document.layers[0].pixels.as_ref().unwrap().bytes());assert_eq!(reopened.layers[0].mask,i.document.layers[0].mask);}
#[test]fn legacy_pascal_names_use_macintosh_roman_without_unicode_extension(){let mut layer=pixel("Unused");layer.legacy=Some(vec![b'C',b'a',b'f',0x8e]);for big in [false,true]{let imported=psd::read(&fixture(big,true,std::slice::from_ref(&layer)),MAX_PIXELS,MAX_PIXELS).unwrap();assert_eq!(imported.document.layers[0].name,"Café");}}
#[test]fn an_unsupported_editable_record_without_cached_pixels_has_a_truthful_skip_notice(){let mut layer=pixel("Missing preview");layer.no_pixels=true;block(&mut layer.extra,b"TySh",&[]);let imported=psd::read(&fixture(false,true,&[layer,pixel("Background")]),MAX_PIXELS,MAX_PIXELS).unwrap();assert_eq!(imported.document.layers.len(),1);assert_eq!(imported.document.layers[0].name,"Background");assert!(imported.conversions.iter().any(|c|c.layer_name=="Missing preview"&&c.message.contains("no cached pixels and was skipped")));assert!(!imported.conversions.iter().any(|c|c.message.contains("imported as pixels")));}
#[test]fn supported_curves_and_colorized_hue_adjustments_retain_their_parameters(){let mut curves=pixel("Curves");let mut data=vec![0];u16(&mut data,4);u16(&mut data,1);u16(&mut data,3);for n in [0,0,200,128,255,255]{u16(&mut data,n);}block(&mut curves.extra,b"curv",&data);let mut hue=pixel("Colorize");let mut data=Vec::new();u16(&mut data,2);data.extend([1,0]);for n in [45,20,5,0,0,0]{u16(&mut data,n);}block(&mut hue.extra,b"hue2",&data);let imported=psd::read(&fixture(false,true,&[pixel("Photo"),hue,curves]),MAX_PIXELS,MAX_PIXELS).unwrap();let c=imported.document.layers[2].extra.adjustment.as_ref().unwrap();assert_eq!(c.curves.channels[0][1],CurvePoint{x:128.,y:200.});let h=imported.document.layers[1].extra.adjustment.as_ref().unwrap().hsv_settings.as_ref().unwrap();assert!(h.colorize);assert_eq!(h.adjustments[&ColorRange::Master].hue,45.);assert_eq!(h.adjustments[&ColorRange::Master].saturation,20.);assert!(imported.document.layers[1].pixels.is_none());}
fn identifier(v:&mut Vec<u8>,name:&str){u32(v,if name.len()==4{0}else{name.len() as u32});v.extend(name.as_bytes());}
fn unicode(v:&mut Vec<u8>,s:&str){let units:Vec<_>=s.encode_utf16().collect();u32(v,units.len() as u32);for unit in units{u16(v,unit);}}
fn descriptor(fields:Vec<(&str,&str,Vec<u8>)>)->Vec<u8>{let mut v=Vec::new();unicode(&mut v,"");identifier(&mut v,"null");u32(&mut v,fields.len() as u32);for (key,kind,data) in fields{identifier(&mut v,key);v.extend(kind.as_bytes());v.extend(data);}v}
fn versioned(data:Vec<u8>)->Vec<u8>{let mut v=Vec::new();u32(&mut v,16);v.extend(data);v}
#[test]fn photoshop_text_retains_editable_content_and_first_style(){let mut layer=pixel("Text");let mut text=Vec::new();unicode(&mut text,"Editable 中文😀\r");let engine=b"<< /ResourceDict << /FontSet [ << /Name (ArialMT) >> ] >> /EngineDict << /StyleRun << /RunArray [ << /StyleSheet << /StyleSheetData << /Font 0 /FontSize 18 /Tracking 150 /FillColor << /Values [ 1 0 1 0 ] >> >> >> >> ] >> /ParagraphRun << /RunArray [ << /ParagraphSheet << /Properties << /Justification 2 >> >> >> ] >> >> >>";let mut data=Vec::new();u32(&mut data,engine.len() as u32);data.extend(engine);let mut tysh=Vec::new();u16(&mut tysh,1);for n in [1f64,0.,0.,1.,20.,30.]{tysh.extend(n.to_be_bytes());}u16(&mut tysh,50);tysh.extend(versioned(descriptor(vec![("Txt ","TEXT",text),("EngineData","tdta",data)])));block(&mut layer.extra,b"TySh",&tysh);
    let imported=psd::read(&fixture(false,true,&[layer]),MAX_PIXELS,MAX_PIXELS).unwrap();let style=imported.document.layers[0].extra.text.as_ref().unwrap();assert_eq!(style["content"],"Editable 中文😀");assert_eq!(style["fontName"],"ArialMT");assert_eq!(style["fontSize"].as_f64(),Some(18.0));assert_eq!(style["green"].as_f64(),Some(1.0));assert_eq!(style["alignment"],"Center");assert!((style["tracking"].as_f64().unwrap()-2.7).abs()<1e-8);assert!(imported.conversions.iter().any(|n|n.message.contains("Editable text")));let reopened=open_package(&save_package(&imported.document).unwrap()).unwrap();assert_eq!(reopened.layers[0].extra.text,imported.document.layers[0].extra.text);}
#[test]fn supported_fill_shape_is_editable_and_redrawn(){let mut layer=pixel("Live rectangle");let color=descriptor(vec![("Rd  ","doub",255f64.to_be_bytes().to_vec()),("Grn ","doub",0f64.to_be_bytes().to_vec()),("Bl  ","doub",0f64.to_be_bytes().to_vec())]);block(&mut layer.extra,b"SoCo",&versioned(descriptor(vec![("Clr ","Objc",color)])));let bounds=descriptor(vec![("Left","UntF",[b"#Pxl".as_slice(),&0f64.to_be_bytes()].concat()),("Top ","UntF",[b"#Pxl".as_slice(),&0f64.to_be_bytes()].concat()),("Rght","UntF",[b"#Pxl".as_slice(),&16f64.to_be_bytes()].concat()),("Btom","UntF",[b"#Pxl".as_slice(),&12f64.to_be_bytes()].concat())]);let mut origin=1u32.to_be_bytes().to_vec();origin.extend(versioned(descriptor(vec![("keyOriginType","long",1u32.to_be_bytes().to_vec()),("keyOriginShapeBBox","Objc",bounds)])));block(&mut layer.extra,b"vogk",&origin);
    let imported=psd::read(&fixture(false,true,&[layer]),MAX_PIXELS,MAX_PIXELS).unwrap();let layer=&imported.document.layers[0];assert_eq!(layer.extra.shape.as_ref().unwrap()["kind"],"Rectangle");assert_eq!(layer.pixels.as_ref().unwrap().width,16);assert_eq!(layer.pixels.as_ref().unwrap().pixel(8,6),[255,0,0,255]);assert!(imported.conversions.is_empty());assert!(psd::read(&fixture(false,true,&[pixel("Other")]),0,MAX_PIXELS).is_err());}
