import { test,expect,type Page } from "@playwright/test";
import {clickMenu,noisePngBase64} from "./helpers";
async function setup(page:Page){await page.goto("/");await expect(page.getByTestId("engine-ready")).toBeVisible();const b64=await page.evaluate(noisePngBase64);await page.evaluate(data=>{const api=(window as any).__compositor;const doc=api.engine.importImage(null,Uint8Array.from(atob(data),(c:string)=>c.charCodeAt(0)),"Photo",null);api.store.getState().openDocument(doc);},b64);}
async function snapshot(page:Page){return page.evaluate(()=>{const api=(window as any).__compositor;const s=api.store.getState();return {depth:s.documents[s.activeId].undoDepth,png:Array.from(api.engine.composite(s.activeId,{x:0,y:0,width:64,height:64},64,64))};});}
async function exposure(page:Page,value:string){await page.getByLabel("Exposure",{exact:true}).fill(value);await page.getByLabel("Exposure",{exact:true}).press("Enter");}
test("diagnostic clipping view is visible at neutral settings and is never baked by OK",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await page.getByRole("combobox",{name:"Clipping view",exact:true}).selectOption("1");await expect.poll(async()=>(await snapshot(page)).png).not.toEqual(before.png);await page.getByTestId("adjust-ok").click();expect(await snapshot(page)).toEqual(before);});
test("Point Color samples the graded layer with HSV saturation under another covering layer",async({page})=>{
  await setup(page);
  await page.evaluate(()=>{const a=(window as any).__compositor,s=a.store.getState(),doc=s.activeId,target=s.documents[doc].activeLayerId;const c=document.createElement("canvas");c.width=64;c.height=64;const ctx=c.getContext("2d")!;ctx.fillStyle="red";ctx.fillRect(0,0,64,64);const data=c.toDataURL().split(",")[1];a.engine.importImage(doc,Uint8Array.from(atob(data),(v:string)=>v.charCodeAt(0)),"Cover",null);a.engine.execute(doc,{type:"SetActiveLayer",id:target});a.store.getState().refresh(doc);a.store.getState().selectLayers([target],target);});
  const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");
  const original=await page.evaluate(()=>{const a=(window as any).__compositor,s=a.store.getState();return a.engine.cameraRawSampleColor(s.activeId,s.adjustEdit.layerId,{x:20,y:20},false);});
  await exposure(page,"1");await expect.poll(()=>page.evaluate(()=>{const a=(window as any).__compositor,s=a.store.getState();return a.engine.cameraRawSampleColor(s.activeId,s.adjustEdit.layerId,{x:20,y:20});})).not.toEqual(original);
  await page.getByText("Point Color",{exact:true}).click();await page.getByRole("button",{name:"Point Color Eyedropper",exact:true}).click();
  const p=await page.evaluate(()=>{const a=(window as any).__compositor,s=a.store.getState(),rgb=a.engine.cameraRawSampleColor(s.activeId,s.adjustEdit.layerId,{x:20,y:20});const composite=a.engine.sampleColor(s.activeId,{x:20,y:20});s.sampleAt({x:20,y:20});return{rgb,composite,points:a.store.getState().adjustEdit.params.settings.mixer.points};});
  expect(p.rgb).not.toEqual(p.composite);expect(p.points).toHaveLength(1);const max=Math.max(...p.rgb),min=Math.min(...p.rgb);expect(p.points[0].luminance).toBeCloseTo((max+min)/2,5);expect(p.points[0].saturation).toBeCloseTo(max===0?0:(max-min)/max,5);
  await page.getByTestId("adjust-cancel").click();expect(await snapshot(page)).toEqual(before);
});
test("Defringe eyedropper centers a hue range on the original layer and Cancel restores pixels",async({page})=>{
  await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await page.getByText("Optics",{exact:true}).click();await page.getByRole("button",{name:"Defringe Eyedropper",exact:true}).click();
  const result=await page.evaluate(()=>{const a=(window as any).__compositor,s=a.store.getState();s.sampleAt({x:20,y:20});return a.store.getState().adjustEdit.params.settings.optics;});
  expect(result.purpleAmount===50||result.greenAmount===50).toBe(true);const span=result.purpleAmount===50?result.purpleHueHigh-result.purpleHueLow:result.greenHueHigh-result.greenHueLow;expect(span).toBeGreaterThan(0);expect(span).toBeLessThanOrEqual(50);
  await page.getByTestId("adjust-cancel").click();expect(await snapshot(page)).toEqual(before);
});
test("grading wheel changes hue and saturation together and remains cancellable",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await page.getByText("Color Grading",{exact:true}).click();const wheel=page.getByRole("group",{name:"Global Color Wheel",exact:true});await wheel.scrollIntoViewIfNeeded();const box=(await wheel.boundingBox())!;await page.mouse.move(box.x+box.width*.9,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.9,{steps:5});await page.mouse.up();const value=await page.evaluate(()=>(window as any).__compositor.store.getState().adjustEdit.params.settings.grading.global);expect(value.hue).toBeGreaterThan(70);expect(value.hue).toBeLessThan(110);expect(value.saturation).toBeGreaterThan(60);expect(value.luminance).toBe(0);await expect.poll(async()=>(await snapshot(page)).png).not.toEqual(before.png);await page.getByTestId("adjust-cancel").click();expect(await snapshot(page)).toEqual(before);});
test("group bypass retains its settings, preview and commit share the bypass, and group Reset is neutral",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await exposure(page,"1");await expect.poll(async()=>(await snapshot(page)).png).not.toEqual(before.png);await page.getByRole("checkbox",{name:"Enable Light",exact:true}).uncheck();await expect.poll(()=>snapshot(page)).toEqual(before);await expect(page.getByRole("spinbutton",{name:"Exposure",exact:true})).toHaveValue("1");await page.getByTestId("adjust-ok").click();expect(await snapshot(page)).toEqual(before);await clickMenu(page,"Filter","filter-camera-raw");await exposure(page,"1");await page.getByRole("button",{name:"Reset Light",exact:true}).click();await expect(page.getByRole("spinbutton",{name:"Exposure",exact:true})).toHaveValue("0");await page.getByTestId("adjust-ok").click();expect(await snapshot(page)).toEqual(before);});
test("Camera Raw preview changes pixels, toggles off, and Cancel retains exact source and history",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await exposure(page,"1");await expect.poll(async()=>(await snapshot(page)).png).not.toEqual(before.png);expect((await snapshot(page)).depth).toBe(before.depth);await page.getByTestId("adjust-preview").uncheck();expect(await snapshot(page)).toEqual(before);await page.getByTestId("adjust-preview").check();await page.getByTestId("adjust-cancel").click();expect(await snapshot(page)).toEqual(before);});
test("Camera Raw applies one undo step, undo restores source, and Reset is an exact no-op",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");await exposure(page,"1");await page.getByTestId("adjust-ok").click();const after=await snapshot(page);expect(after.depth).toBe(before.depth+1);expect(after.png).not.toEqual(before.png);await page.keyboard.press("Control+z");expect(await snapshot(page)).toEqual(before);await clickMenu(page,"Filter","filter-camera-raw");await exposure(page,"-1.2");await page.getByTestId("adjust-reset").click();await page.getByTestId("adjust-ok").click();expect(await snapshot(page)).toEqual(before);});
test("point curve drags one handle, keeps endpoints and increasing input, and right-click removes it",async({page})=>{await setup(page);await clickMenu(page,"Filter","filter-camera-raw");await page.getByText("Curve",{exact:true}).click();const graph=page.getByTestId("camera-raw-curve");await graph.scrollIntoViewIfNeeded();const box=(await graph.boundingBox())!;await page.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height*.2,{steps:8});await page.mouse.up();const points=await page.evaluate(()=>(window as any).__compositor.store.getState().adjustEdit.params.settings.curve.rgb);expect(points).toHaveLength(3);expect(points[0].x).toBe(0);expect(points[2].x).toBe(1);expect(points[1].x).toBeGreaterThan(.7);await graph.click({button:"right",position:{x:points[1].x*box.width,y:(1-points[1].y)*box.height}});expect(await graph.locator("circle").count()).toBe(2);await page.getByTestId("adjust-cancel").click();});
test("all Camera Raw groups are available and Point Color edits remain cancellable",async({page})=>{await setup(page);const before=await snapshot(page);await clickMenu(page,"Filter","filter-camera-raw");for(const name of ["Curve","Color Mixer","Point Color","Color Grading","Effects","Detail","Optics","Geometry","Calibration"]){await expect(page.locator("summary").filter({hasText:new RegExp(`^${name}$`)})).toBeVisible();}await page.getByText("Point Color",{exact:true}).click();await page.getByRole("button",{name:"Add Point Color",exact:true}).click();await page.getByLabel("Color 1 Hue Shift",{exact:true}).fill("35");await page.getByLabel("Color 1 Hue Shift",{exact:true}).press("Enter");await page.getByTestId("adjust-cancel").click();expect(await snapshot(page)).toEqual(before);});
