import {test,expect,type Page} from "@playwright/test";
import {clickMenu,solidPngBase64} from "./helpers";
async function setup(page:Page){await page.goto("/");await expect(page.getByTestId("engine-ready")).toBeVisible();const png=await page.evaluate(solidPngBase64,{width:128,height:96,color:"#804020"});await page.evaluate(data=>{
    const api=(window as any).__compositor,bridge=api.bridge;const pixels=Uint8Array.from(atob(data),(c:string)=>c.charCodeAt(0));bridge.rawCalls=[];bridge.rawCancelled=[];
    bridge.rawInspect=async()=>({decoder:"Test sensor adapter",width:128,height:96,make:"Test",model:"Bayer",asShotTemperature:5000,asShotTint:2,whiteBalanceEstimate:true,sensorDecoded:false});
    bridge.rawDevelop=async(path:string,settings:unknown,preview:boolean,token:string)=>{bridge.rawCalls.push({path,settings,preview,token});await new Promise(r=>setTimeout(r,40));if(bridge.rawCancelled.includes(token))throw Error("Cancelled");return pixels.slice();};
    bridge.rawCancel=async(token:string)=>{bridge.rawCancelled.push(token);};bridge.setNextPick("C:/test/real-sensor.dng");
  },png);}
test("RAW Cancel imports nothing and releases the file-operation guard",async({page})=>{await setup(page);await clickMenu(page,"File","import");await expect(page.getByRole("dialog",{name:"Develop Camera RAW"})).toBeVisible();await expect(page.getByTestId("raw-preview")).toBeVisible();await page.getByRole("button",{name:"Cancel",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);const state=await page.evaluate(()=>{const s=(window as any).__compositor.store.getState();return{count:s.order.length,busy:s.busy};});expect(state).toEqual({count:0,busy:false});});
test("Enter commits the field without importing; Reset returns to As Shot and Import performs full development",async({page})=>{await setup(page);await clickMenu(page,"File","import");await expect(page.getByTestId("raw-preview")).toBeVisible();await page.getByRole("spinbutton",{name:"Exposure",exact:true}).fill("1.5");await page.getByRole("spinbutton",{name:"Exposure",exact:true}).press("Enter");await expect(page.getByRole("dialog",{name:"Develop Camera RAW"})).toBeVisible();expect(await page.evaluate(()=>(window as any).__compositor.store.getState().order.length)).toBe(0);await page.getByRole("button",{name:"Reset to As Shot"}).click();await expect(page.getByRole("spinbutton",{name:"Exposure",exact:true})).toHaveValue("0");await expect(page.getByRole("spinbutton",{name:"Temperature",exact:true})).toHaveValue("5000");await expect(page.getByRole("spinbutton",{name:"Tint",exact:true})).toHaveValue("2");await page.getByRole("button",{name:"Import",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);const result=await page.evaluate(()=>{const api=(window as any).__compositor,s=api.store.getState();return{doc:s.documents[s.activeId],calls:api.bridge.rawCalls};});expect(result.doc.width).toBe(128);expect(result.doc.height).toBe(96);expect(result.doc.layers).toHaveLength(1);expect(result.doc.isModified).toBe(true);expect(result.calls.filter((c:any)=>!c.preview)).toHaveLength(1);expect(result.calls.at(-1).settings).toEqual({exposure:0,temperature:5000,tint:2,tone:1});});
test("a failed full RAW development keeps the dialog and never imports a partial document",async({page})=>{await setup(page);await page.evaluate(()=>{const b=(window as any).__compositor.bridge,original=b.rawDevelop;b.rawDevelop=async(...args:any[])=>{if(!args[2])throw Error("Sensor decode failed");return original(...args);};});await clickMenu(page,"File","import");await expect(page.getByTestId("raw-preview")).toBeVisible();await page.getByRole("button",{name:"Import",exact:true}).click();await expect(page.getByRole("alert")).toContainText("Sensor decode failed");expect(await page.evaluate(()=>(window as any).__compositor.store.getState().order.length)).toBe(0);await page.getByRole("button",{name:"Cancel",exact:true}).click();});
